services:
  postgres:
    image: postgres:16-alpine
    container_name: chu-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - chu_postgres_data:/var/lib/postgresql/data

volumes:
  chu_postgres_data:
